# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-05 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_photo',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
