# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-08 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0004_auto_20190908_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='scheduled_time',
            field=models.DateTimeField(default=None),
        ),
    ]
